# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.game_boxscore_team_team_stats_team_skater_stats import GameBoxscoreTeamTeamStatsTeamSkaterStats

class TestGameBoxscoreTeamTeamStatsTeamSkaterStats(unittest.TestCase):
    """GameBoxscoreTeamTeamStatsTeamSkaterStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameBoxscoreTeamTeamStatsTeamSkaterStats:
        """Test GameBoxscoreTeamTeamStatsTeamSkaterStats
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameBoxscoreTeamTeamStatsTeamSkaterStats`
        """
        model = GameBoxscoreTeamTeamStatsTeamSkaterStats()
        if include_optional:
            return GameBoxscoreTeamTeamStatsTeamSkaterStats(
                goals = 6,
                pim = 6,
                shots = 30,
                power_play_percentage = '0.0',
                power_play_goals = 0,
                power_play_opportunities = 1,
                face_off_win_percentage = '59.3',
                blocked = 21,
                takeaways = 9,
                giveaways = 6,
                hits = 15
            )
        else:
            return GameBoxscoreTeamTeamStatsTeamSkaterStats(
        )
        """

    def testGameBoxscoreTeamTeamStatsTeamSkaterStats(self):
        """Test GameBoxscoreTeamTeamStatsTeamSkaterStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
