# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.game_play_players_inner import GamePlayPlayersInner

class TestGamePlayPlayersInner(unittest.TestCase):
    """GamePlayPlayersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GamePlayPlayersInner:
        """Test GamePlayPlayersInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GamePlayPlayersInner`
        """
        model = GamePlayPlayersInner()
        if include_optional:
            return GamePlayPlayersInner(
                player = openapi_client.models.game_play_players_inner_player.GamePlay_players_inner_player(
                    id = 8476881, 
                    full_name = 'Tomas Hertl', 
                    link = '/api/v1/people/8476881', ),
                player_type = 'Winner'
            )
        else:
            return GamePlayPlayersInner(
        )
        """

    def testGamePlayPlayersInner(self):
        """Test GamePlayPlayersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
