# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.stats_api import StatsApi


class TestStatsApi(unittest.TestCase):
    """StatsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StatsApi()

    def tearDown(self) -> None:
        pass

    def test_get_stat_types(self) -> None:
        """Test case for get_stat_types

        Get all available NHL statistic types.
        """
        pass


if __name__ == '__main__':
    unittest.main()
