# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.schedule_game_teams_away import ScheduleGameTeamsAway

class TestScheduleGameTeamsAway(unittest.TestCase):
    """ScheduleGameTeamsAway unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduleGameTeamsAway:
        """Test ScheduleGameTeamsAway
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduleGameTeamsAway`
        """
        model = ScheduleGameTeamsAway()
        if include_optional:
            return ScheduleGameTeamsAway(
                league_record = openapi_client.models.schedule_game_teams_away_league_record.ScheduleGame_teams_away_leagueRecord(
                    wins = 23, 
                    losses = 27, 
                    ot = 4, 
                    type = 'league', ),
                score = 4,
                team = openapi_client.models.schedule_game_teams_away_team.ScheduleGame_teams_away_team(
                    id = 22, 
                    name = 'Edmonton Oilers', 
                    link = '/api/v1/teams/22', )
            )
        else:
            return ScheduleGameTeamsAway(
        )
        """

    def testScheduleGameTeamsAway(self):
        """Test ScheduleGameTeamsAway"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
