# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.schedule_game_teams_away_team import ScheduleGameTeamsAwayTeam

class TestScheduleGameTeamsAwayTeam(unittest.TestCase):
    """ScheduleGameTeamsAwayTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduleGameTeamsAwayTeam:
        """Test ScheduleGameTeamsAwayTeam
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduleGameTeamsAwayTeam`
        """
        model = ScheduleGameTeamsAwayTeam()
        if include_optional:
            return ScheduleGameTeamsAwayTeam(
                id = 22,
                name = 'Edmonton Oilers',
                link = '/api/v1/teams/22'
            )
        else:
            return ScheduleGameTeamsAwayTeam(
        )
        """

    def testScheduleGameTeamsAwayTeam(self):
        """Test ScheduleGameTeamsAwayTeam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
