# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.game_period import GamePeriod

class TestGamePeriod(unittest.TestCase):
    """GamePeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GamePeriod:
        """Test GamePeriod
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GamePeriod`
        """
        model = GamePeriod()
        if include_optional:
            return GamePeriod(
                period_type = 'REGULAR',
                start_time = '2018-02-11T03:09:50Z',
                end_time = '2018-02-11T03:44:47Z',
                num = 1,
                ordinal_num = '1st',
                home = openapi_client.models.game_period_home.GamePeriod_home(
                    goals = 2, 
                    shots_on_goal = 14, 
                    rink_side = 'left', ),
                away = openapi_client.models.game_period_away.GamePeriod_away(
                    goals = 0, 
                    shots_on_goal = 9, 
                    rink_side = 'right', )
            )
        else:
            return GamePeriod(
        )
        """

    def testGamePeriod(self):
        """Test GamePeriod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
