# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.standings_api import StandingsApi


class TestStandingsApi(unittest.TestCase):
    """StandingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StandingsApi()

    def tearDown(self) -> None:
        pass

    def test_get_standing_types(self) -> None:
        """Test case for get_standing_types

        Get all available NHL standing types.
        """
        pass

    def test_get_standings(self) -> None:
        """Test case for get_standings

        Get NHL division standings.
        """
        pass

    def test_get_standings_by_type(self) -> None:
        """Test case for get_standings_by_type

        Get NHL standings for a specific standing type.
        """
        pass


if __name__ == '__main__':
    unittest.main()
