# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.draft_drafts_inner_rounds_inner_picks_inner_prospect import DraftDraftsInnerRoundsInnerPicksInnerProspect

class TestDraftDraftsInnerRoundsInnerPicksInnerProspect(unittest.TestCase):
    """DraftDraftsInnerRoundsInnerPicksInnerProspect unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DraftDraftsInnerRoundsInnerPicksInnerProspect:
        """Test DraftDraftsInnerRoundsInnerPicksInnerProspect
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DraftDraftsInnerRoundsInnerPicksInnerProspect`
        """
        model = DraftDraftsInnerRoundsInnerPicksInnerProspect()
        if include_optional:
            return DraftDraftsInnerRoundsInnerPicksInnerProspect(
                id = 65242,
                full_name = 'Nico Hischier',
                link = '/api/v1/draft/prospects/65242'
            )
        else:
            return DraftDraftsInnerRoundsInnerPicksInnerProspect(
        )
        """

    def testDraftDraftsInnerRoundsInnerPicksInnerProspect(self):
        """Test DraftDraftsInnerRoundsInnerPicksInnerProspect"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
