# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.photo_cuts import PhotoCuts

class TestPhotoCuts(unittest.TestCase):
    """PhotoCuts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PhotoCuts:
        """Test PhotoCuts
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PhotoCuts`
        """
        model = PhotoCuts()
        if include_optional:
            return PhotoCuts(
                aspect_ratio = '16:9',
                width = 2568,
                height = 1444,
                src = 'https://nhl.bamcontent.com/images/photos/295824704/2568x1444/cut.jpg',
                at2x = 'https://nhl.bamcontent.com/images/photos/295824704/2568x1444/cut.jpg',
                at3x = 'https://nhl.bamcontent.com/images/photos/295824704/2568x1444/cut.jpg'
            )
        else:
            return PhotoCuts(
        )
        """

    def testPhotoCuts(self):
        """Test PhotoCuts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
