# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.draft import Draft

class TestDraft(unittest.TestCase):
    """Draft unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Draft:
        """Test Draft
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Draft`
        """
        model = Draft()
        if include_optional:
            return Draft(
                copyright = '',
                drafts = [
                    openapi_client.models.draft_drafts_inner.Draft_drafts_inner(
                        draft_year = 2017, 
                        rounds = [
                            openapi_client.models.draft_drafts_inner_rounds_inner.Draft_drafts_inner_rounds_inner(
                                round_number = 1, 
                                round = 1, 
                                picks = [
                                    openapi_client.models.draft_drafts_inner_rounds_inner_picks_inner.Draft_drafts_inner_rounds_inner_picks_inner(
                                        year = 2017, 
                                        round = '1', 
                                        pick_overall = 1, 
                                        pick_in_round = 1, 
                                        team = openapi_client.models.draft_drafts_inner_rounds_inner_picks_inner_team.Draft_drafts_inner_rounds_inner_picks_inner_team(
                                            id = 1, 
                                            name = 'New Jersey Devils', 
                                            link = '/api/v1/teams/1', ), 
                                        prospect = openapi_client.models.draft_drafts_inner_rounds_inner_picks_inner_prospect.Draft_drafts_inner_rounds_inner_picks_inner_prospect(
                                            id = 65242, 
                                            full_name = 'Nico Hischier', 
                                            link = '/api/v1/draft/prospects/65242', ), )
                                    ], )
                            ], )
                    ]
            )
        else:
            return Draft(
        )
        """

    def testDraft(self):
        """Test Draft"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
