# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.game_official_official import GameOfficialOfficial

class TestGameOfficialOfficial(unittest.TestCase):
    """GameOfficialOfficial unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameOfficialOfficial:
        """Test GameOfficialOfficial
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameOfficialOfficial`
        """
        model = GameOfficialOfficial()
        if include_optional:
            return GameOfficialOfficial(
                id = 2071,
                full_name = 'Tim Peel',
                link = '/api/v1/people/2071'
            )
        else:
            return GameOfficialOfficial(
        )
        """

    def testGameOfficialOfficial(self):
        """Test GameOfficialOfficial"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
