# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.game_decision_player import GameDecisionPlayer

class TestGameDecisionPlayer(unittest.TestCase):
    """GameDecisionPlayer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameDecisionPlayer:
        """Test GameDecisionPlayer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameDecisionPlayer`
        """
        model = GameDecisionPlayer()
        if include_optional:
            return GameDecisionPlayer(
                id = 8477180,
                full_name = 'Aaron Dell',
                link = '/api/v1/people/8477180'
            )
        else:
            return GameDecisionPlayer(
        )
        """

    def testGameDecisionPlayer(self):
        """Test GameDecisionPlayer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
