# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.game_media_nhltv import GameMediaNHLTV

class TestGameMediaNHLTV(unittest.TestCase):
    """GameMediaNHLTV unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameMediaNHLTV:
        """Test GameMediaNHLTV
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameMediaNHLTV`
        """
        model = GameMediaNHLTV()
        if include_optional:
            return GameMediaNHLTV(
                title = 'NHLTV',
                platform = 'web',
                items = [
                    openapi_client.models.game_media_nhltv_items_inner.GameMediaNHLTV_items_inner(
                        guid = 'dbb39fa8-6679-4b22-a8c5-71eb5e39b462', 
                        media_state = 'MEDIA_ARCHIVE', 
                        media_playback_id = '57463703', 
                        media_feed_type = 'HOME', 
                        call_letters = 'NBCS-CA', 
                        event_id = '221-1007449', 
                        language = 'eng', 
                        free_game = True, 
                        feed_name = '', 
                        game_plus = True, )
                    ]
            )
        else:
            return GameMediaNHLTV(
        )
        """

    def testGameMediaNHLTV(self):
        """Test GameMediaNHLTV"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
