# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.standings_records_inner_league import StandingsRecordsInnerLeague

class TestStandingsRecordsInnerLeague(unittest.TestCase):
    """StandingsRecordsInnerLeague unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StandingsRecordsInnerLeague:
        """Test StandingsRecordsInnerLeague
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StandingsRecordsInnerLeague`
        """
        model = StandingsRecordsInnerLeague()
        if include_optional:
            return StandingsRecordsInnerLeague(
                id = 133,
                name = 'National Hockey League',
                link = '/api/v1/league/133'
            )
        else:
            return StandingsRecordsInnerLeague(
        )
        """

    def testStandingsRecordsInnerLeague(self):
        """Test StandingsRecordsInnerLeague"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
