# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.game_boxscore_team_coaches_inner import GameBoxscoreTeamCoachesInner

class TestGameBoxscoreTeamCoachesInner(unittest.TestCase):
    """GameBoxscoreTeamCoachesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameBoxscoreTeamCoachesInner:
        """Test GameBoxscoreTeamCoachesInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameBoxscoreTeamCoachesInner`
        """
        model = GameBoxscoreTeamCoachesInner()
        if include_optional:
            return GameBoxscoreTeamCoachesInner(
                person = openapi_client.models.game_boxscore_team_coaches_inner_person.GameBoxscoreTeam_coaches_inner_person(
                    full_name = 'Peter DeBoer', 
                    link = '/api/v1/people/null', ),
                position = openapi_client.models.game_boxscore_team_coaches_inner_position.GameBoxscoreTeam_coaches_inner_position(
                    code = 'HC', 
                    name = 'Head Coach', 
                    type = 'Head Coach', 
                    abbreviation = 'Head Coach', )
            )
        else:
            return GameBoxscoreTeamCoachesInner(
        )
        """

    def testGameBoxscoreTeamCoachesInner(self):
        """Test GameBoxscoreTeamCoachesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
