# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.standings_records_inner_team_records_inner import StandingsRecordsInnerTeamRecordsInner

class TestStandingsRecordsInnerTeamRecordsInner(unittest.TestCase):
    """StandingsRecordsInnerTeamRecordsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StandingsRecordsInnerTeamRecordsInner:
        """Test StandingsRecordsInnerTeamRecordsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StandingsRecordsInnerTeamRecordsInner`
        """
        model = StandingsRecordsInnerTeamRecordsInner()
        if include_optional:
            return StandingsRecordsInnerTeamRecordsInner(
                team = openapi_client.models.player_current_team.Player_currentTeam(
                    id = 28, 
                    name = 'San Jose Sharks', 
                    link = '/api/v1/teams/28', ),
                league_record = openapi_client.models.schedule_game_teams_home_league_record.ScheduleGame_teams_home_leagueRecord(
                    wins = 29, 
                    losses = 18, 
                    ot = 8, 
                    type = 'league', ),
                goals_against = 154,
                goals_scored = 162,
                points = 66,
                division_rank = '2',
                conference_rank = '7',
                league_rank = '11',
                wild_card_rank = '0',
                row = 26,
                games_played = 55,
                streak = openapi_client.models.standings_records_inner_team_records_inner_streak.Standings_records_inner_teamRecords_inner_streak(
                    streak_type = 'wins', 
                    streak_number = 1, 
                    streak_code = 'W1', ),
                last_updated = '2018-02-11T00:57:18Z'
            )
        else:
            return StandingsRecordsInnerTeamRecordsInner(
        )
        """

    def testStandingsRecordsInnerTeamRecordsInner(self):
        """Test StandingsRecordsInnerTeamRecordsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
