# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.team_next_game_schedule_dates_inner import TeamNextGameScheduleDatesInner

class TestTeamNextGameScheduleDatesInner(unittest.TestCase):
    """TeamNextGameScheduleDatesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamNextGameScheduleDatesInner:
        """Test TeamNextGameScheduleDatesInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamNextGameScheduleDatesInner`
        """
        model = TeamNextGameScheduleDatesInner()
        if include_optional:
            return TeamNextGameScheduleDatesInner(
                var_date = 'Fri Feb 09 19:00:00 EST 2018',
                total_items = 1,
                total_events = 0,
                total_games = 1,
                total_matches = 0,
                games = [
                    openapi_client.models.team_next_game_schedule_dates_inner_games_inner.Team_nextGameSchedule_dates_inner_games_inner(
                        game_pk = 2017020851, 
                        link = '/api/v1/game/2017020851/feed/live', 
                        game_type = 'R', 
                        season = '20172018', 
                        game_date = '2018-02-11T03:00Z', 
                        status = openapi_client.models.team_next_game_schedule_dates_inner_games_inner_status.Team_nextGameSchedule_dates_inner_games_inner_status(
                            abstract_game_state = 'Live', 
                            coded_game_state = '3', 
                            detailed_state = 'In Progress', 
                            status_code = '2', 
                            start_time_tbd = True, ), 
                        teams = openapi_client.models.team_next_game_schedule_dates_inner_games_inner_teams.Team_nextGameSchedule_dates_inner_games_inner_teams(
                            away = openapi_client.models.team_next_game_schedule_dates_inner_games_inner_teams_away.Team_nextGameSchedule_dates_inner_games_inner_teams_away(
                                league_record = openapi_client.models.team_next_game_schedule_dates_inner_games_inner_teams_away_league_record.Team_nextGameSchedule_dates_inner_games_inner_teams_away_leagueRecord(
                                    wins = 23, 
                                    losses = 26, 
                                    ot = 4, 
                                    type = 'league', ), 
                                score = 0, 
                                team = openapi_client.models.team_next_game_schedule_dates_inner_games_inner_teams_away_team.Team_nextGameSchedule_dates_inner_games_inner_teams_away_team(
                                    id = 22, 
                                    name = 'Edmonton Oilers', 
                                    link = '/api/v1/teams/22', ), ), 
                            home = openapi_client.models.team_next_game_schedule_dates_inner_games_inner_teams_home.Team_nextGameSchedule_dates_inner_games_inner_teams_home(
                                score = 2, ), ), 
                        venue = openapi_client.models.game_game_data_venue.Game_gameData_venue(
                            name = 'SAP Center at San Jose', 
                            link = '/api/v1/venues/null', ), 
                        content = openapi_client.models.schedule_game_content.ScheduleGame_content(
                            link = '/api/v1/game/2017020851/content', ), )
                    ],
                events = [
                    None
                    ],
                matches = [
                    None
                    ]
            )
        else:
            return TeamNextGameScheduleDatesInner(
        )
        """

    def testTeamNextGameScheduleDatesInner(self):
        """Test TeamNextGameScheduleDatesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
