# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.game_boxscore_team_players_position import GameBoxscoreTeamPlayersPosition

class TestGameBoxscoreTeamPlayersPosition(unittest.TestCase):
    """GameBoxscoreTeamPlayersPosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameBoxscoreTeamPlayersPosition:
        """Test GameBoxscoreTeamPlayersPosition
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameBoxscoreTeamPlayersPosition`
        """
        model = GameBoxscoreTeamPlayersPosition()
        if include_optional:
            return GameBoxscoreTeamPlayersPosition(
                code = 'D',
                name = 'Defenseman',
                type = 'Defenseman',
                abbreviation = 'D'
            )
        else:
            return GameBoxscoreTeamPlayersPosition(
        )
        """

    def testGameBoxscoreTeamPlayersPosition(self):
        """Test GameBoxscoreTeamPlayersPosition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
