# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.draft_prospect import DraftProspect

class TestDraftProspect(unittest.TestCase):
    """DraftProspect unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DraftProspect:
        """Test DraftProspect
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DraftProspect`
        """
        model = DraftProspect()
        if include_optional:
            return DraftProspect(
                id = 65242,
                full_name = 'Nico Hischier',
                link = '/api/v1/draft/prospects/65242',
                first_name = 'Nico',
                last_name = 'Hischier',
                birth_date = 'Sun Jan 03 19:00:00 EST 1999',
                birth_city = 'Naters',
                birth_country = 'CHE',
                nationality = 'CHE',
                height = '6' 2"',
                weight = 179,
                shoots_catches = 'L',
                primary_position = openapi_client.models.draft_prospect_primary_position.DraftProspect_primaryPosition(
                    code = 'C', 
                    name = 'Center', 
                    type = 'Forward', 
                    abbreviation = 'C', ),
                prospect_category = openapi_client.models.draft_prospect_prospect_category.DraftProspect_prospectCategory(
                    id = 1, 
                    short_name = 'NA Skater', 
                    name = 'North American Skater', ),
                amateur_team = openapi_client.models.draft_prospect_amateur_team.DraftProspect_amateurTeam(
                    link = '/api/v1/teams/null', ),
                amateur_league = openapi_client.models.draft_prospect_amateur_league.DraftProspect_amateurLeague(
                    link = '/api/v1/league/null', ),
                ranks = None
            )
        else:
            return DraftProspect(
        )
        """

    def testDraftProspect(self):
        """Test DraftProspect"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
