# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.standings_records_inner_team_records_inner_streak import StandingsRecordsInnerTeamRecordsInnerStreak

class TestStandingsRecordsInnerTeamRecordsInnerStreak(unittest.TestCase):
    """StandingsRecordsInnerTeamRecordsInnerStreak unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StandingsRecordsInnerTeamRecordsInnerStreak:
        """Test StandingsRecordsInnerTeamRecordsInnerStreak
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StandingsRecordsInnerTeamRecordsInnerStreak`
        """
        model = StandingsRecordsInnerTeamRecordsInnerStreak()
        if include_optional:
            return StandingsRecordsInnerTeamRecordsInnerStreak(
                streak_type = 'wins',
                streak_number = 1,
                streak_code = 'W1'
            )
        else:
            return StandingsRecordsInnerTeamRecordsInnerStreak(
        )
        """

    def testStandingsRecordsInnerTeamRecordsInnerStreak(self):
        """Test StandingsRecordsInnerTeamRecordsInnerStreak"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
