# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.game_game_data_datetime import GameGameDataDatetime

class TestGameGameDataDatetime(unittest.TestCase):
    """GameGameDataDatetime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameGameDataDatetime:
        """Test GameGameDataDatetime
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameGameDataDatetime`
        """
        model = GameGameDataDatetime()
        if include_optional:
            return GameGameDataDatetime(
                date_time = '2018-02-11T03:00Z',
                end_date_time = '2018-02-11T05:30:42Z'
            )
        else:
            return GameGameDataDatetime(
        )
        """

    def testGameGameDataDatetime(self):
        """Test GameGameDataDatetime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
