# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.game_boxscore_team_players_person import GameBoxscoreTeamPlayersPerson

class TestGameBoxscoreTeamPlayersPerson(unittest.TestCase):
    """GameBoxscoreTeamPlayersPerson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameBoxscoreTeamPlayersPerson:
        """Test GameBoxscoreTeamPlayersPerson
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameBoxscoreTeamPlayersPerson`
        """
        model = GameBoxscoreTeamPlayersPerson()
        if include_optional:
            return GameBoxscoreTeamPlayersPerson(
                id = 8471709,
                full_name = 'Marc-Edouard Vlasic',
                link = '/api/v1/people/8471709',
                shoots_catches = 'L',
                roster_status = 'Y'
            )
        else:
            return GameBoxscoreTeamPlayersPerson(
        )
        """

    def testGameBoxscoreTeamPlayersPerson(self):
        """Test GameBoxscoreTeamPlayersPerson"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
