# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.game_game_data_teams import GameGameDataTeams

class TestGameGameDataTeams(unittest.TestCase):
    """GameGameDataTeams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameGameDataTeams:
        """Test GameGameDataTeams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameGameDataTeams`
        """
        model = GameGameDataTeams()
        if include_optional:
            return GameGameDataTeams(
                away = openapi_client.models.team.Team(
                    id = 28, 
                    name = 'San Jose Sharks', 
                    link = '/api/v1/teams/28', 
                    venue = openapi_client.models.venue.Venue(
                        name = 'SAP Center at San Jose', 
                        link = '/api/v1/venues/null', 
                        city = 'San Jose', 
                        time_zone = openapi_client.models.venue_time_zone.Venue_timeZone(
                            id = 'America/Los_Angeles', 
                            offset = -8, 
                            tz = 'PST', ), ), 
                    abbreviation = 'SJS', 
                    tri_code = 'SJS', 
                    team_name = 'Sharks', 
                    location_name = 'San Jose', 
                    first_year_of_play = 1990, 
                    division = openapi_client.models.standings_records_inner_division.Standings_records_inner_division(
                        id = 15, 
                        name = 'Pacific', 
                        link = '/api/v1/divisions/15', ), 
                    conference = openapi_client.models.division_conference.Division_conference(
                        id = 5, 
                        name = 'Western', 
                        link = '/api/v1/conferences/5', ), 
                    franchise = openapi_client.models.franchise.Franchise(
                        id = 29, 
                        name = 'Sharks', 
                        link = '/api/v1/franchises/29', ), 
                    roster = openapi_client.models.team_roster.Team_roster(), 
                    next_game_schedule = openapi_client.models.team_next_game_schedule.Team_nextGameSchedule(
                        total_items = 1, 
                        total_events = 0, 
                        total_games = 1, 
                        total_matches = 0, 
                        dates = [
                            openapi_client.models.team_next_game_schedule_dates_inner.Team_nextGameSchedule_dates_inner(
                                date = 'Fri Feb 09 19:00:00 EST 2018', 
                                total_items = 1, 
                                total_events = 0, 
                                total_games = 1, 
                                total_matches = 0, 
                                games = [
                                    openapi_client.models.team_next_game_schedule_dates_inner_games_inner.Team_nextGameSchedule_dates_inner_games_inner(
                                        game_pk = 2017020851, 
                                        link = '/api/v1/game/2017020851/feed/live', 
                                        game_type = 'R', 
                                        season = '20172018', 
                                        game_date = '2018-02-11T03:00Z', 
                                        status = openapi_client.models.team_next_game_schedule_dates_inner_games_inner_status.Team_nextGameSchedule_dates_inner_games_inner_status(
                                            abstract_game_state = 'Live', 
                                            coded_game_state = '3', 
                                            detailed_state = 'In Progress', 
                                            status_code = '2', 
                                            start_time_tbd = True, ), 
                                        teams = openapi_client.models.team_next_game_schedule_dates_inner_games_inner_teams.Team_nextGameSchedule_dates_inner_games_inner_teams(
                                            home = openapi_client.models.team_next_game_schedule_dates_inner_games_inner_teams_home.Team_nextGameSchedule_dates_inner_games_inner_teams_home(
                                                league_record = openapi_client.models.team_next_game_schedule_dates_inner_games_inner_teams_home_league_record.Team_nextGameSchedule_dates_inner_games_inner_teams_home_leagueRecord(
                                                    wins = 28, 
                                                    losses = 18, 
                                                    ot = 8, 
                                                    type = 'league', ), 
                                                score = 2, 
                                                team = openapi_client.models.player_current_team.Player_currentTeam(
                                                    id = 28, 
                                                    name = 'San Jose Sharks', 
                                                    link = '/api/v1/teams/28', ), ), ), 
                                        content = openapi_client.models.schedule_game_content.ScheduleGame_content(
                                            link = '/api/v1/game/2017020851/content', ), )
                                    ], 
                                events = [
                                    None
                                    ], 
                                matches = [
                                    None
                                    ], )
                            ], ), 
                    short_name = 'San Jose', 
                    official_site_url = 'http://www.sjsharks.com', 
                    franchise_id = 29, 
                    active = True, ),
                home = openapi_client.models.team.Team(
                    id = 28, 
                    name = 'San Jose Sharks', 
                    link = '/api/v1/teams/28', 
                    venue = openapi_client.models.venue.Venue(
                        name = 'SAP Center at San Jose', 
                        link = '/api/v1/venues/null', 
                        city = 'San Jose', 
                        time_zone = openapi_client.models.venue_time_zone.Venue_timeZone(
                            id = 'America/Los_Angeles', 
                            offset = -8, 
                            tz = 'PST', ), ), 
                    abbreviation = 'SJS', 
                    tri_code = 'SJS', 
                    team_name = 'Sharks', 
                    location_name = 'San Jose', 
                    first_year_of_play = 1990, 
                    division = openapi_client.models.standings_records_inner_division.Standings_records_inner_division(
                        id = 15, 
                        name = 'Pacific', 
                        link = '/api/v1/divisions/15', ), 
                    conference = openapi_client.models.division_conference.Division_conference(
                        id = 5, 
                        name = 'Western', 
                        link = '/api/v1/conferences/5', ), 
                    franchise = openapi_client.models.franchise.Franchise(
                        id = 29, 
                        name = 'Sharks', 
                        link = '/api/v1/franchises/29', ), 
                    roster = openapi_client.models.team_roster.Team_roster(), 
                    next_game_schedule = openapi_client.models.team_next_game_schedule.Team_nextGameSchedule(
                        total_items = 1, 
                        total_events = 0, 
                        total_games = 1, 
                        total_matches = 0, 
                        dates = [
                            openapi_client.models.team_next_game_schedule_dates_inner.Team_nextGameSchedule_dates_inner(
                                date = 'Fri Feb 09 19:00:00 EST 2018', 
                                total_items = 1, 
                                total_events = 0, 
                                total_games = 1, 
                                total_matches = 0, 
                                games = [
                                    openapi_client.models.team_next_game_schedule_dates_inner_games_inner.Team_nextGameSchedule_dates_inner_games_inner(
                                        game_pk = 2017020851, 
                                        link = '/api/v1/game/2017020851/feed/live', 
                                        game_type = 'R', 
                                        season = '20172018', 
                                        game_date = '2018-02-11T03:00Z', 
                                        status = openapi_client.models.team_next_game_schedule_dates_inner_games_inner_status.Team_nextGameSchedule_dates_inner_games_inner_status(
                                            abstract_game_state = 'Live', 
                                            coded_game_state = '3', 
                                            detailed_state = 'In Progress', 
                                            status_code = '2', 
                                            start_time_tbd = True, ), 
                                        teams = openapi_client.models.team_next_game_schedule_dates_inner_games_inner_teams.Team_nextGameSchedule_dates_inner_games_inner_teams(
                                            away = openapi_client.models.team_next_game_schedule_dates_inner_games_inner_teams_away.Team_nextGameSchedule_dates_inner_games_inner_teams_away(
                                                league_record = openapi_client.models.team_next_game_schedule_dates_inner_games_inner_teams_away_league_record.Team_nextGameSchedule_dates_inner_games_inner_teams_away_leagueRecord(
                                                    wins = 23, 
                                                    losses = 26, 
                                                    ot = 4, 
                                                    type = 'league', ), 
                                                score = 0, 
                                                team = openapi_client.models.team_next_game_schedule_dates_inner_games_inner_teams_away_team.Team_nextGameSchedule_dates_inner_games_inner_teams_away_team(
                                                    id = 22, 
                                                    name = 'Edmonton Oilers', 
                                                    link = '/api/v1/teams/22', ), ), ), 
                                        content = openapi_client.models.schedule_game_content.ScheduleGame_content(
                                            link = '/api/v1/game/2017020851/content', ), )
                                    ], 
                                events = [
                                    None
                                    ], 
                                matches = [
                                    None
                                    ], )
                            ], ), 
                    short_name = 'San Jose', 
                    official_site_url = 'http://www.sjsharks.com', 
                    franchise_id = 29, 
                    active = True, )
            )
        else:
            return GameGameDataTeams(
        )
        """

    def testGameGameDataTeams(self):
        """Test GameGameDataTeams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
