# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.divisions_api import DivisionsApi


class TestDivisionsApi(unittest.TestCase):
    """DivisionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DivisionsApi()

    def tearDown(self) -> None:
        pass

    def test_get_division(self) -> None:
        """Test case for get_division

        Get an NHL division.
        """
        pass

    def test_get_divisions(self) -> None:
        """Test case for get_divisions

        Get all current NHL divisions.
        """
        pass


if __name__ == '__main__':
    unittest.main()
