# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.game_linescore_shootout_info import GameLinescoreShootoutInfo

class TestGameLinescoreShootoutInfo(unittest.TestCase):
    """GameLinescoreShootoutInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameLinescoreShootoutInfo:
        """Test GameLinescoreShootoutInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameLinescoreShootoutInfo`
        """
        model = GameLinescoreShootoutInfo()
        if include_optional:
            return GameLinescoreShootoutInfo(
                away = openapi_client.models.game_linescore_shootout_info_away.GameLinescore_shootoutInfo_away(
                    scores = 0, 
                    attempts = 0, ),
                home = openapi_client.models.game_linescore_shootout_info_away.GameLinescore_shootoutInfo_away(
                    scores = 0, 
                    attempts = 0, )
            )
        else:
            return GameLinescoreShootoutInfo(
        )
        """

    def testGameLinescoreShootoutInfo(self):
        """Test GameLinescoreShootoutInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
