# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.standings import Standings

class TestStandings(unittest.TestCase):
    """Standings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Standings:
        """Test Standings
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Standings`
        """
        model = Standings()
        if include_optional:
            return Standings(
                copyright = '',
                records = [
                    openapi_client.models.standings_records_inner.Standings_records_inner(
                        standings_type = 'regularSeason', 
                        league = openapi_client.models.standings_records_inner_league.Standings_records_inner_league(
                            id = 133, 
                            name = 'National Hockey League', 
                            link = '/api/v1/league/133', ), 
                        division = openapi_client.models.standings_records_inner_division.Standings_records_inner_division(
                            id = 15, 
                            name = 'Pacific', 
                            link = '/api/v1/divisions/15', ), 
                        conference = openapi_client.models.division_conference.Division_conference(
                            id = 5, 
                            name = 'Western', 
                            link = '/api/v1/conferences/5', ), 
                        team_records = [
                            openapi_client.models.standings_records_inner_team_records_inner.Standings_records_inner_teamRecords_inner(
                                team = openapi_client.models.player_current_team.Player_currentTeam(
                                    id = 28, 
                                    name = 'San Jose Sharks', 
                                    link = '/api/v1/teams/28', ), 
                                league_record = openapi_client.models.schedule_game_teams_home_league_record.ScheduleGame_teams_home_leagueRecord(
                                    wins = 29, 
                                    losses = 18, 
                                    ot = 8, 
                                    type = 'league', ), 
                                goals_against = 154, 
                                goals_scored = 162, 
                                points = 66, 
                                division_rank = '2', 
                                conference_rank = '7', 
                                league_rank = '11', 
                                wild_card_rank = '0', 
                                row = 26, 
                                games_played = 55, 
                                streak = openapi_client.models.standings_records_inner_team_records_inner_streak.Standings_records_inner_teamRecords_inner_streak(
                                    streak_type = 'wins', 
                                    streak_number = 1, 
                                    streak_code = 'W1', ), 
                                last_updated = '2018-02-11T00:57:18Z', )
                            ], )
                    ]
            )
        else:
            return Standings(
        )
        """

    def testStandings(self):
        """Test Standings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
