# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.conferences_api import ConferencesApi


class TestConferencesApi(unittest.TestCase):
    """ConferencesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConferencesApi()

    def tearDown(self) -> None:
        pass

    def test_get_conference(self) -> None:
        """Test case for get_conference

        Get an NHL conference.
        """
        pass

    def test_get_conferences(self) -> None:
        """Test case for get_conferences

        Get all current NHL conferences.
        """
        pass


if __name__ == '__main__':
    unittest.main()
