# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.players_api import PlayersApi


class TestPlayersApi(unittest.TestCase):
    """PlayersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlayersApi()

    def tearDown(self) -> None:
        pass

    def test_get_player(self) -> None:
        """Test case for get_player

        Get an NHL player.
        """
        pass

    def test_get_player_stats(self) -> None:
        """Test case for get_player_stats

        Get specific statistics for an NHL player.
        """
        pass


if __name__ == '__main__':
    unittest.main()
