# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.team_next_game_schedule_dates_inner_games_inner_teams_away_team import TeamNextGameScheduleDatesInnerGamesInnerTeamsAwayTeam

class TestTeamNextGameScheduleDatesInnerGamesInnerTeamsAwayTeam(unittest.TestCase):
    """TeamNextGameScheduleDatesInnerGamesInnerTeamsAwayTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamNextGameScheduleDatesInnerGamesInnerTeamsAwayTeam:
        """Test TeamNextGameScheduleDatesInnerGamesInnerTeamsAwayTeam
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamNextGameScheduleDatesInnerGamesInnerTeamsAwayTeam`
        """
        model = TeamNextGameScheduleDatesInnerGamesInnerTeamsAwayTeam()
        if include_optional:
            return TeamNextGameScheduleDatesInnerGamesInnerTeamsAwayTeam(
                id = 22,
                name = 'Edmonton Oilers',
                link = '/api/v1/teams/22'
            )
        else:
            return TeamNextGameScheduleDatesInnerGamesInnerTeamsAwayTeam(
        )
        """

    def testTeamNextGameScheduleDatesInnerGamesInnerTeamsAwayTeam(self):
        """Test TeamNextGameScheduleDatesInnerGamesInnerTeamsAwayTeam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
