# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.draft_prospect_amateur_team import DraftProspectAmateurTeam

class TestDraftProspectAmateurTeam(unittest.TestCase):
    """DraftProspectAmateurTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DraftProspectAmateurTeam:
        """Test DraftProspectAmateurTeam
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DraftProspectAmateurTeam`
        """
        model = DraftProspectAmateurTeam()
        if include_optional:
            return DraftProspectAmateurTeam(
                link = '/api/v1/teams/null'
            )
        else:
            return DraftProspectAmateurTeam(
        )
        """

    def testDraftProspectAmateurTeam(self):
        """Test DraftProspectAmateurTeam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
