# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.game_editorial_contributor_contributors_inner import GameEditorialContributorContributorsInner

class TestGameEditorialContributorContributorsInner(unittest.TestCase):
    """GameEditorialContributorContributorsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GameEditorialContributorContributorsInner:
        """Test GameEditorialContributorContributorsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GameEditorialContributorContributorsInner`
        """
        model = GameEditorialContributorContributorsInner()
        if include_optional:
            return GameEditorialContributorContributorsInner(
                name = 'Eric Gilmore',
                twitter = ''
            )
        else:
            return GameEditorialContributorContributorsInner(
        )
        """

    def testGameEditorialContributorContributorsInner(self):
        """Test GameEditorialContributorContributorsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
