# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.team_next_game_schedule_dates_inner_games_inner_status import TeamNextGameScheduleDatesInnerGamesInnerStatus

class TestTeamNextGameScheduleDatesInnerGamesInnerStatus(unittest.TestCase):
    """TeamNextGameScheduleDatesInnerGamesInnerStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamNextGameScheduleDatesInnerGamesInnerStatus:
        """Test TeamNextGameScheduleDatesInnerGamesInnerStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamNextGameScheduleDatesInnerGamesInnerStatus`
        """
        model = TeamNextGameScheduleDatesInnerGamesInnerStatus()
        if include_optional:
            return TeamNextGameScheduleDatesInnerGamesInnerStatus(
                abstract_game_state = 'Live',
                coded_game_state = '3',
                detailed_state = 'In Progress',
                status_code = '2',
                start_time_tbd = True
            )
        else:
            return TeamNextGameScheduleDatesInnerGamesInnerStatus(
        )
        """

    def testTeamNextGameScheduleDatesInnerGamesInnerStatus(self):
        """Test TeamNextGameScheduleDatesInnerGamesInnerStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
