# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr
from pydantic import Field
from openapi_client.models.draft_drafts_inner_rounds_inner_picks_inner_prospect import DraftDraftsInnerRoundsInnerPicksInnerProspect
from openapi_client.models.draft_drafts_inner_rounds_inner_picks_inner_team import DraftDraftsInnerRoundsInnerPicksInnerTeam
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DraftDraftsInnerRoundsInnerPicksInner(BaseModel):
    """
    DraftDraftsInnerRoundsInnerPicksInner
    """ # noqa: E501
    year: Optional[Union[StrictFloat, StrictInt]] = None
    round: Optional[StrictStr] = None
    pick_overall: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="pickOverall")
    pick_in_round: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="pickInRound")
    team: Optional[DraftDraftsInnerRoundsInnerPicksInnerTeam] = None
    prospect: Optional[DraftDraftsInnerRoundsInnerPicksInnerProspect] = None
    __properties: ClassVar[List[str]] = ["year", "round", "pickOverall", "pickInRound", "team", "prospect"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DraftDraftsInnerRoundsInnerPicksInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of team
        if self.team:
            _dict['team'] = self.team.to_dict()
        # override the default output from pydantic by calling `to_dict()` of prospect
        if self.prospect:
            _dict['prospect'] = self.prospect.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DraftDraftsInnerRoundsInnerPicksInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "year": obj.get("year"),
            "round": obj.get("round"),
            "pickOverall": obj.get("pickOverall"),
            "pickInRound": obj.get("pickInRound"),
            "team": DraftDraftsInnerRoundsInnerPicksInnerTeam.from_dict(obj.get("team")) if obj.get("team") is not None else None,
            "prospect": DraftDraftsInnerRoundsInnerPicksInnerProspect.from_dict(obj.get("prospect")) if obj.get("prospect") is not None else None
        })
        return _obj


