# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from openapi_client.models.game_game_data_datetime import GameGameDataDatetime
from openapi_client.models.game_game_data_game import GameGameDataGame
from openapi_client.models.game_game_data_status import GameGameDataStatus
from openapi_client.models.game_game_data_teams import GameGameDataTeams
from openapi_client.models.game_game_data_venue import GameGameDataVenue
from openapi_client.models.player import Player
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GameGameData(BaseModel):
    """
    GameGameData
    """ # noqa: E501
    game: Optional[GameGameDataGame] = None
    datetime: Optional[GameGameDataDatetime] = None
    status: Optional[GameGameDataStatus] = None
    teams: Optional[GameGameDataTeams] = None
    players: Optional[Player] = None
    venue: Optional[GameGameDataVenue] = None
    __properties: ClassVar[List[str]] = ["game", "datetime", "status", "teams", "players", "venue"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GameGameData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of game
        if self.game:
            _dict['game'] = self.game.to_dict()
        # override the default output from pydantic by calling `to_dict()` of datetime
        if self.datetime:
            _dict['datetime'] = self.datetime.to_dict()
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict['status'] = self.status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of teams
        if self.teams:
            _dict['teams'] = self.teams.to_dict()
        # override the default output from pydantic by calling `to_dict()` of players
        if self.players:
            _dict['players'] = self.players.to_dict()
        # override the default output from pydantic by calling `to_dict()` of venue
        if self.venue:
            _dict['venue'] = self.venue.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GameGameData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "game": GameGameDataGame.from_dict(obj.get("game")) if obj.get("game") is not None else None,
            "datetime": GameGameDataDatetime.from_dict(obj.get("datetime")) if obj.get("datetime") is not None else None,
            "status": GameGameDataStatus.from_dict(obj.get("status")) if obj.get("status") is not None else None,
            "teams": GameGameDataTeams.from_dict(obj.get("teams")) if obj.get("teams") is not None else None,
            "players": Player.from_dict(obj.get("players")) if obj.get("players") is not None else None,
            "venue": GameGameDataVenue.from_dict(obj.get("venue")) if obj.get("venue") is not None else None
        })
        return _obj


