# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from openapi_client.models.game_boxscore_teams import GameBoxscoreTeams
from openapi_client.models.game_official import GameOfficial
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GameBoxscore(BaseModel):
    """
    GameBoxscore
    """ # noqa: E501
    teams: Optional[GameBoxscoreTeams] = None
    officials: Optional[List[GameOfficial]] = None
    __properties: ClassVar[List[str]] = ["teams", "officials"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GameBoxscore from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of teams
        if self.teams:
            _dict['teams'] = self.teams.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in officials (list)
        _items = []
        if self.officials:
            for _item in self.officials:
                if _item:
                    _items.append(_item.to_dict())
            _dict['officials'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GameBoxscore from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "teams": GameBoxscoreTeams.from_dict(obj.get("teams")) if obj.get("teams") is not None else None,
            "officials": [GameOfficial.from_dict(_item) for _item in obj.get("officials")] if obj.get("officials") is not None else None
        })
        return _obj


