# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr
from pydantic import Field
from openapi_client.models.game_play_about_goals import GamePlayAboutGoals
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GamePlayAbout(BaseModel):
    """
    GamePlayAbout
    """ # noqa: E501
    event_idx: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="eventIdx")
    event_id: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="eventId")
    period: Optional[Union[StrictFloat, StrictInt]] = None
    period_type: Optional[StrictStr] = Field(default=None, alias="periodType")
    ordinal_num: Optional[StrictStr] = Field(default=None, alias="ordinalNum")
    period_time: Optional[StrictStr] = Field(default=None, alias="periodTime")
    period_time_remaining: Optional[StrictStr] = Field(default=None, alias="periodTimeRemaining")
    date_time: Optional[datetime] = Field(default=None, alias="dateTime")
    goals: Optional[GamePlayAboutGoals] = None
    __properties: ClassVar[List[str]] = ["eventIdx", "eventId", "period", "periodType", "ordinalNum", "periodTime", "periodTimeRemaining", "dateTime", "goals"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GamePlayAbout from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of goals
        if self.goals:
            _dict['goals'] = self.goals.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GamePlayAbout from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "eventIdx": obj.get("eventIdx"),
            "eventId": obj.get("eventId"),
            "period": obj.get("period"),
            "periodType": obj.get("periodType"),
            "ordinalNum": obj.get("ordinalNum"),
            "periodTime": obj.get("periodTime"),
            "periodTimeRemaining": obj.get("periodTimeRemaining"),
            "dateTime": obj.get("dateTime"),
            "goals": GamePlayAboutGoals.from_dict(obj.get("goals")) if obj.get("goals") is not None else None
        })
        return _obj


