# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from openapi_client.models.game_play_about import GamePlayAbout
from openapi_client.models.game_play_coordinates import GamePlayCoordinates
from openapi_client.models.game_play_players_inner import GamePlayPlayersInner
from openapi_client.models.game_play_result import GamePlayResult
from openapi_client.models.game_play_team import GamePlayTeam
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GamePlay(BaseModel):
    """
    GamePlay
    """ # noqa: E501
    players: Optional[List[GamePlayPlayersInner]] = None
    result: Optional[GamePlayResult] = None
    about: Optional[GamePlayAbout] = None
    coordinates: Optional[GamePlayCoordinates] = None
    team: Optional[GamePlayTeam] = None
    __properties: ClassVar[List[str]] = ["players", "result", "about", "coordinates", "team"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GamePlay from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in players (list)
        _items = []
        if self.players:
            for _item in self.players:
                if _item:
                    _items.append(_item.to_dict())
            _dict['players'] = _items
        # override the default output from pydantic by calling `to_dict()` of result
        if self.result:
            _dict['result'] = self.result.to_dict()
        # override the default output from pydantic by calling `to_dict()` of about
        if self.about:
            _dict['about'] = self.about.to_dict()
        # override the default output from pydantic by calling `to_dict()` of coordinates
        if self.coordinates:
            _dict['coordinates'] = self.coordinates.to_dict()
        # override the default output from pydantic by calling `to_dict()` of team
        if self.team:
            _dict['team'] = self.team.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GamePlay from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "players": [GamePlayPlayersInner.from_dict(_item) for _item in obj.get("players")] if obj.get("players") is not None else None,
            "result": GamePlayResult.from_dict(obj.get("result")) if obj.get("result") is not None else None,
            "about": GamePlayAbout.from_dict(obj.get("about")) if obj.get("about") is not None else None,
            "coordinates": GamePlayCoordinates.from_dict(obj.get("coordinates")) if obj.get("coordinates") is not None else None,
            "team": GamePlayTeam.from_dict(obj.get("team")) if obj.get("team") is not None else None
        })
        return _obj


