# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictBool, StrictFloat, StrictInt
from pydantic import Field
from openapi_client.models.game_boxscore_team_team import GameBoxscoreTeamTeam
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GameLinescoreTeam(BaseModel):
    """
    GameLinescoreTeam
    """ # noqa: E501
    team: Optional[GameBoxscoreTeamTeam] = None
    goals: Optional[Union[StrictFloat, StrictInt]] = None
    shots_on_goal: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="shotsOnGoal")
    goalie_pulled: Optional[StrictBool] = Field(default=None, alias="goaliePulled")
    num_skaters: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="numSkaters")
    power_play: Optional[StrictBool] = Field(default=None, alias="powerPlay")
    __properties: ClassVar[List[str]] = ["team", "goals", "shotsOnGoal", "goaliePulled", "numSkaters", "powerPlay"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GameLinescoreTeam from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of team
        if self.team:
            _dict['team'] = self.team.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GameLinescoreTeam from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "team": GameBoxscoreTeamTeam.from_dict(obj.get("team")) if obj.get("team") is not None else None,
            "goals": obj.get("goals"),
            "shotsOnGoal": obj.get("shotsOnGoal"),
            "goaliePulled": obj.get("goaliePulled"),
            "numSkaters": obj.get("numSkaters"),
            "powerPlay": obj.get("powerPlay")
        })
        return _obj


